export const products = [
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Volkswagen",
    model: "Picanto",
    description:
      "The original hot hatch blends a torquey turbo-four with a terrific chassis and a practical four-door hatch layout that continue its legacy of affordable fun.",
    price: 4000,
    brand: "Volkswagen",
    category: "Sedan",
    inStock: true,
    image: "https://pngimg.com/uploads/volkswagen/volkswagen_PNG1821.png",
  },
];
